// ============================================================
// mock_data.dart  –  Seeded data for nv.elon
// ============================================================
import 'models.dart';

final kCategories = const [
  AppCategory(
    id: 'real-estate',
    name: 'Real Estate',
    uzName: 'Uy-joy sotuvi',
    icon: '🏠',
    subcategories: [
      AppSubcategory(
        id: 'apartments',
        name: 'Apartments',
        uzName: 'Kvartiralar',
      ),
      AppSubcategory(
        id: 'houses',
        name: 'Houses & Villas',
        uzName: 'Hovli va Dacha',
      ),
      AppSubcategory(id: 'land', name: 'Land Plots', uzName: 'Er uchastkalari'),
    ],
  ),
  AppCategory(
    id: 'electronics',
    name: 'Electronics & Tech',
    uzName: 'Elektronika',
    icon: '💻',
    subcategories: [
      AppSubcategory(id: 'phones', name: 'Smartphones', uzName: 'Telefonlar'),
      AppSubcategory(id: 'laptops', name: 'Laptops', uzName: 'Noutbuklar'),
      AppSubcategory(
        id: 'accessories',
        name: 'Accessories',
        uzName: 'Aksessuarlar',
      ),
    ],
  ),
  AppCategory(
    id: 'commercial-farming',
    name: 'Commercial Farming',
    uzName: "Firma Xo'jaligi",
    icon: '🚜',
    subcategories: [
      AppSubcategory(
        id: 'machinery',
        name: 'Heavy Machinery',
        uzName: "Og'ir Texnika",
      ),
      AppSubcategory(
        id: 'irrigation',
        name: 'Irrigation',
        uzName: 'Sug\'orish',
      ),
      AppSubcategory(id: 'wholesale', name: 'Wholesale', uzName: 'Ulgurji'),
    ],
  ),
  AppCategory(
    id: 'local-farming',
    name: 'Local Farming',
    uzName: "Dehqon Xo'jaligi",
    icon: '🌾',
    subcategories: [
      AppSubcategory(
        id: 'grains',
        name: 'Grains & Crops',
        uzName: 'Don mahsulotlari',
      ),
      AppSubcategory(
        id: 'livestock',
        name: 'Livestock',
        uzName: "Mol, qo'y, quyon",
      ),
      AppSubcategory(
        id: 'poultry',
        name: 'Poultry & Eggs',
        uzName: 'Tovuq, tuxum',
      ),
    ],
  ),
];

final List<Listing> kMockListings = [
  Listing(
    id: '1',
    title: 'Toshkent Cityda zamonaviy 3 xonali kvartira',
    description:
        'Toshkent City nufuzli majmuasida to\'liq jihozlangan yuqori darajadagi kvartira. 4-qavat, 88 kv.m. Aqlli uy tizimi, yer osti avtoturargohi, 24/7 xavfsizlik.',
    price: 125000,
    categoryId: 'real-estate',
    subcategoryId: 'apartments',
    location: 'Toshkent City, Toshkent',
    phone: '+998901234567',
    date: 'Bugun, 14:20',
    colorTag: 'blue',
    views: 142,
    sellerName: 'Tashkent Real Estate LLC',
    isCompany: true,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '2',
    title: 'DJI Agras T40 Qishloq xo\'jaligi droni (Yangi)',
    description:
        'Yangi DJI Agras T40 aniq purkash droni. Sig\'imi 40 litr, yuk ko\'tarish quvvati 50 kg. To\'siqlarni chetlab o\'tish tizimi bilan soatiga 21 gektargacha maydonni qoplaydi.',
    price: 16200,
    categoryId: 'electronics',
    subcategoryId: 'accessories',
    location: 'Yunusobod, Toshkent',
    phone: '+998949876543',
    date: 'Bugun, 09:15',
    colorTag: 'purple',
    views: 389,
    sellerName: 'Smart Agrotech Tashkent',
    isCompany: true,
    imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '3',
    title: 'John Deere 6140M Traktori – 2022 yilda ishlab chiqarilgan',
    description:
        'Aʼlo holatda, atigi 1200 ish soati. 140 ot kuchi dvigateli. Rasmiy dilerda texnik xizmat ko\'rsatilgan. GPS avtomatik boshqaruv tizimi mavjud.',
    price: 78000,
    categoryId: 'commercial-farming',
    subcategoryId: 'machinery',
    location: 'Jizzax viloyati',
    phone: '+998934567890',
    date: 'Kecha, 18:30',
    colorTag: 'teal',
    views: 520,
    sellerName: 'Jizzax Agro Cluster',
    isCompany: true,
    imageUrl: 'https://images.unsplash.com/photo-1530268578403-bf6e898031e4?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '4',
    title: 'Golshtin zotli sog\'in sigir – kuniga 28L sut',
    description:
        'Yuqori mahsuldor Golshtin sigiri, 2-laktatsiya. Kuniga 28–32 litr sut beradi. Barcha emlashlar qilingan, veterinar sertifikati bor.',
    price: 1800,
    categoryId: 'local-farming',
    subcategoryId: 'livestock',
    location: 'Samarqand tumani',
    phone: '+998971112233',
    date: 'Kecha, 11:05',
    colorTag: 'green',
    views: 245,
    sellerName: 'Sherzod Aka',
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '5',
    title: 'Oliy sifatli Alanga guruchi – Ulgurji (1.5 tonna)',
    description:
        'Xorazm viloyatidan yangi yig\'ib olingan Alanga navli guruch. Ikki marta sayqallangan, oliy eksport navi. Yetkazib berish xizmati mavjud.',
    price: 1200,
    categoryId: 'local-farming',
    subcategoryId: 'grains',
    location: 'Gurlan, Xorazm',
    phone: '+998998887766',
    date: '15-Iyun, 16:45',
    colorTag: 'green',
    views: 112,
    sellerName: 'Xorazm Don Agro',
    isCompany: true,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '6',
    title: 'MacBook Pro 16" M3 Max – 36 GB / 1 TB',
    description:
        'Ideal holatdagi Space Black MacBook Pro. Batareya quvvati 99%, atigi 28 ta sikl. iOS dasturlash uchun foydalanilgan. Qutisi va hamma narsasi bor.',
    price: 2650,
    categoryId: 'electronics',
    subcategoryId: 'laptops',
    location: 'Mirzo Ulugbek, Toshkent',
    phone: '+998907775544',
    date: '14-Iyun, 10:00',
    colorTag: 'purple',
    views: 405,
    sellerName: 'Jahongir',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '7',
    title: 'Lohmann Brown kunlik jo\'jalar – 500 dona',
    description:
        '1 kunlik Lohmann Brown zotli emlangan jo\'jalar. Yashab ketish darajasi 98% dan yuqori, tuxum yo\'nalishidagi fermalar uchun ajoyib tanlov.',
    price: 450,
    categoryId: 'local-farming',
    subcategoryId: 'poultry',
    location: 'Quva, Farg\'ona',
    phone: '+998916543210',
    date: '13-Iyun, 08:30',
    colorTag: 'green',
    views: 187,
    sellerName: 'Farg\'ona Parranda',
    isCompany: true,
    imageUrl: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '8',
    title: 'Tomchilatib sug\'orish tizimi – 10 gektar uchun',
    description:
        'To\'liq professional tomchilatib sug\'orish to\'plami. Filtrlar, nasoslar, tarqatish quvurlari va klapanlarni o\'z ichiga oladi. Suvni 40% gacha tejaydi.',
    price: 11500,
    categoryId: 'commercial-farming',
    subcategoryId: 'irrigation',
    location: 'Namangan tumani',
    phone: '+998953334455',
    date: '12-Iyun, 15:10',
    colorTag: 'teal',
    views: 312,
    sellerName: 'Vodiy Agrotex',
    isCompany: true,
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=600&auto=format&fit=crop&q=80',
  ),
  Listing(
    id: '9',
    title: 'Hisor zotdor qo\'chqori – 95 kg (1.5 yosh)',
    description:
        'Toza zotli Hisor qo\'chqori, vazni 95 kg. Sifatli ko\'paytirish uchun ajoyib nasl. Sog\'lom va faol, tabiiy ozuqa va don aralashmasi bilan boqilgan.',
    price: 380,
    categoryId: 'local-farming',
    subcategoryId: 'livestock',
    location: 'Parkent, Toshkent vil.',
    phone: '+998984445566',
    date: '12-Iyun, 11:20',
    colorTag: 'green',
    views: 298,
    sellerName: 'Zokirjon Aka',
    imageUrl: 'https://images.unsplash.com/photo-1484557985045-edd9b37b161b?w=600&auto=format&fit=crop&q=80',
  ),
];
